# SPDX-FileCopyrightText: 2023-2024 Tampere region
#
# SPDX-License-Identifier: LGPL-2.1-or-later

version = 1
SPDX-PackageName = "trevaka"
SPDX-PackageDownloadLocation = "https://github.com/Tampere/trevaka"

[[annotations]]
path = ".github/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017-2020 City of Tampere"
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = "frontend/.yarn/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2016-present Yarn Contributors"
SPDX-License-Identifier = "BSD-2-Clause"
SPDX-FileComment = "Directory also includes code with other licenses and other copyright holders but those are clearly identified\n  in the source code with prefixed comments. Only the not-explicitly licensed portions are licensed with information\n  described here."

[[annotations]]
path = "**.gitignore"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 City of Tampere"
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = ".gitmodules"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 City of Tampere"
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = "frontend/package.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 City of Tampere"
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = "frontend/tsconfig.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 City of Tampere"
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = "**.yarnrc.yml"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021-2023 City of Tampere"
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = "frontend/yarn.lock"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 City of Tampere"
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = ".env"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 City of Tampere"
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = "auth/realms/**.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 City of Tampere"
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = "infra/deploy/.terraform-version"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023-2024 Tampere region"
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = "infra/deploy/.terraform.lock.hcl"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023-2024 Tampere region"
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = "service/build.gradle.kts"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 City of Tampere"
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = "service/src/test/resources/invoice-client/**.xml"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 City of Tampere"
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = "service/src/test/resources/payment-client/**.xml"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023-2024 Tampere region"
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = "**/gradlew**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2007-2020 The original author or authors <info@gradle.com>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/gradle/wrapper/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2007-2020 The original author or authors <info@gradle.com>"
SPDX-License-Identifier = "Apache-2.0"
